serverport:                8080
servertls:                 false
servertimeout:             5
serverdialtimeout:         10
servertlshandshaketimeout: 5
serverfilecrt:             "ssl/test.crt"
serverfilekey:             "ssl/test.key"
authapitype:               "dev"
authapiendpoint:           "http://localhost/jwt.php"
filesrootdirectory:        "./files"