server:
    port: 8080
    timeout: 5
    dialtimeout: 10
    tlsenabled: true
    tlshandshaketimeout: 5
    tlsfilecrt: "ssl/test.crt"
    tlsfilekey: "ssl/test.key"

handler:
    rootdirectory: "./files"
    authtype: "dev"
    jwtloginendpoint: "http://localhost:8000/login"
